// lib/shared/table_registry.dart
//
// The single owner of table/chair data. Admin CRUD, the QR deep link and the
// staff/customer pickers all go through here, so the lookup rules live in one
// place.
//
// Model — one document per table, chairs as an array on the parent:
//
//   tables/{autoId}
//     name:      String   e.g. 'Table 001'   (written to orders' table_no)
//     sortOrder: int
//     chairs:    [ { id: String, no: int } ]
//     createdAt: Timestamp
//
// `chair.id` is a stable opaque id, so renumbering a chair never invalidates a
// QR code that has already been printed. `chair.no` is unique across the whole
// restaurant — that is what lets a waiter type a chair number on its own and
// get back exactly one table.
import 'package:cloud_firestore/cloud_firestore.dart';

class ChairEntry {
  const ChairEntry({required this.id, required this.no});

  final String id;
  final int no;

  Map<String, dynamic> toMap() => {'id': id, 'no': no};

  static ChairEntry? fromMap(dynamic raw) {
    if (raw is! Map) return null;
    final id = (raw['id'] ?? '').toString();
    final no = (raw['no'] as num?)?.toInt();
    if (id.isEmpty || no == null) return null;
    return ChairEntry(id: id, no: no);
  }

  /// Ids only have to be unique within the restaurant, not globally.
  static String newId() =>
      'c${DateTime.now().microsecondsSinceEpoch.toRadixString(36)}';
}

class TableDoc {
  const TableDoc({
    required this.id,
    required this.name,
    required this.sortOrder,
    required this.chairs,
  });

  final String id;
  final String name;
  final int sortOrder;
  final List<ChairEntry> chairs;

  static TableDoc fromDoc(DocumentSnapshot doc) {
    final data = doc.data() as Map<String, dynamic>? ?? {};
    final rawChairs = data['chairs'] as List<dynamic>? ?? [];
    final chairs = rawChairs
        .map(ChairEntry.fromMap)
        .whereType<ChairEntry>()
        .toList()
      ..sort((a, b) => a.no.compareTo(b.no));

    return TableDoc(
      id: doc.id,
      name: (data['name'] ?? '').toString(),
      sortOrder: (data['sortOrder'] as num?)?.toInt() ?? 0,
      chairs: chairs,
    );
  }

  ChairEntry? chairById(String chairId) {
    for (final chair in chairs) {
      if (chair.id == chairId) return chair;
    }
    return null;
  }
}

/// A resolved seat: which table, and which chair on it (null for a table-only
/// QR code).
class SeatSelection {
  const SeatSelection({required this.table, this.chair});

  final TableDoc table;
  final ChairEntry? chair;

  String get tableName => table.name;
  String get chairNo => chair == null ? '' : chair!.no.toString();
  String get label =>
      chair == null ? table.name : '${table.name} · Chair ${chair!.no}';
}

/// The outcome of looking up whatever was typed into a chair field.
class ChairTextResult {
  const ChairTextResult({
    required this.rawText,
    this.table,
    this.chair,
    this.unresolved = const [],
    this.spansMultipleTables = false,
  });

  /// Exactly what the user typed — always what gets stored as `chair_no`.
  final String rawText;

  /// The table owning the first chair that resolved, if any.
  final TableDoc? table;

  /// Set only when a single chair was typed.
  final ChairEntry? chair;

  /// Numbers that are not registered. Not an error: unknown numbers are still
  /// allowed through, just with a warning.
  final List<String> unresolved;

  final bool spansMultipleTables;

  bool get resolved => table != null;
  bool get hasUnresolved => unresolved.isNotEmpty;
}

/// What a scanned QR code turned out to be.
class ScanPayload {
  const ScanPayload({
    this.tableId,
    this.chairId,
    this.chairNo,
    this.plainText,
  });

  /// Ids from a chair/table QR generated by this app.
  final String? tableId;
  final String? chairId;

  /// The number printed on the chair, from a `?n=` sticker.
  final int? chairNo;

  /// An older QR code (or any unrecognised text) — the raw string, which the
  /// pickers still accept as a free-text table name.
  final String? plainText;

  bool get hasIds => tableId != null && tableId!.isNotEmpty;

  bool get hasChairNumber => chairNo != null;

  /// Whether this scan can be turned into a real seat.
  bool get isResolvable => hasIds || hasChairNumber;
}

/// Roles allowed to enter a table/chair by hand instead of scanning.
///
/// One definition for the whole app: the two table pickers used to disagree
/// (the home sheet left out 'staff'), so the same waiter could get the manual
/// tab on one screen but not the other.
bool isStaffRole(String? role) {
  const staffRoles = {'cashier', 'admin', 'staff', 'waiter'};
  return staffRoles.contains((role ?? '').toLowerCase().trim());
}

/// Reads a user's role.
///
/// User documents are created with the auth uid as the document id, but some
/// older screens look them up by a `uid` field instead, so both are tried
/// rather than silently treating a staff member as a customer.
Future<String> fetchUserRole(String uid) async {
  final users = FirebaseFirestore.instance.collection('user');
  try {
    final doc = await users.doc(uid).get();
    final role = (doc.data()?['role'] as String?)?.trim();
    if (role != null && role.isNotEmpty) return role.toLowerCase();

    final query = await users.where('uid', isEqualTo: uid).limit(1).get();
    if (query.docs.isNotEmpty) {
      final queried = (query.docs.first.data()['role'] as String?)?.trim();
      if (queried != null && queried.isNotEmpty) return queried.toLowerCase();
    }
  } catch (_) {
    // Fall through to the default below.
  }
  return 'customer';
}

class TableRegistry {
  static final CollectionReference<Map<String, dynamic>> _collection =
      FirebaseFirestore.instance.collection('tables');

  // ---------------------------------------------------------------- reading

  static Stream<List<TableDoc>> streamTables() {
    return _collection.snapshots().map(_sorted);
  }

  static Future<List<TableDoc>> loadTables() async {
    final snap = await _collection.get();
    return _sorted(snap);
  }

  static List<TableDoc> _sorted(QuerySnapshot snapshot) {
    final tables = snapshot.docs.map(TableDoc.fromDoc).toList();
    // Sorted client-side (like the itemNo lists elsewhere in the admin panel)
    // so no Firestore index is needed.
    tables.sort((a, b) {
      final byOrder = a.sortOrder.compareTo(b.sortOrder);
      if (byOrder != 0) return byOrder;
      return a.name.toLowerCase().compareTo(b.name.toLowerCase());
    });
    return tables;
  }

  static Future<TableDoc?> tableById(String tableId) async {
    if (tableId.isEmpty) return null;
    final doc = await _collection.doc(tableId).get();
    if (!doc.exists) return null;
    return TableDoc.fromDoc(doc);
  }

  // ------------------------------------------------------------- resolving

  /// Resolves a scanned QR code — a single document read.
  static Future<SeatSelection?> resolveByIds(
    String tableId,
    String? chairId,
  ) async {
    final table = await tableById(tableId);
    if (table == null) return null;

    if (chairId == null || chairId.isEmpty) {
      return SeatSelection(table: table);
    }

    final chair = table.chairById(chairId);
    // An unknown chair id (renamed/removed seat) still identifies the table,
    // which beats sending the guest back to a dead end.
    return SeatSelection(table: table, chair: chair);
  }

  /// Resolves the chair number a waiter typed. Chair numbers are unique across
  /// the restaurant, so at most one seat matches.
  static Future<SeatSelection?> resolveByChairNumber(int chairNo) async {
    final tables = await loadTables();
    for (final table in tables) {
      for (final chair in table.chairs) {
        if (chair.no == chairNo) {
          return SeatSelection(table: table, chair: chair);
        }
      }
    }
    return null;
  }

  /// Resolves whatever a staff member typed into a chair field.
  ///
  /// The chair fields already invite several seats at once ("e.g. 1, 2, 3"), so
  /// every number is resolved and the raw text is always preserved for
  /// `chair_no`; the caller only needs [ChairTextResult.table] to fill in the
  /// table.
  static Future<ChairTextResult> resolveChairText(String raw) async {
    final text = raw.trim();
    if (text.isEmpty) return const ChairTextResult(rawText: '');

    final numbers = text
        .split(RegExp(r'[,\s/;]+'))
        .map((token) => int.tryParse(token.trim()))
        .whereType<int>()
        .toList();

    if (numbers.isEmpty) {
      return ChairTextResult(rawText: text, unresolved: [text]);
    }

    final tables = await loadTables();
    TableDoc? firstTable;
    ChairEntry? firstChair;
    final unresolved = <String>[];
    var sameTable = true;

    for (final no in numbers) {
      TableDoc? owner;
      ChairEntry? match;
      for (final table in tables) {
        for (final chair in table.chairs) {
          if (chair.no == no) {
            owner = table;
            match = chair;
            break;
          }
        }
        if (owner != null) break;
      }

      if (owner == null) {
        unresolved.add(no.toString());
        continue;
      }
      if (firstTable == null) {
        firstTable = owner;
        firstChair = match;
      } else if (firstTable.id != owner.id) {
        sameTable = false;
      }
    }

    return ChairTextResult(
      rawText: text,
      table: firstTable,
      chair: numbers.length == 1 ? firstChair : null,
      unresolved: unresolved,
      spansMultipleTables: !sameTable,
    );
  }

  // -------------------------------------------------------------- QR codes

  /// The URL encoded into a chair's QR code.
  ///
  /// [origin] defaults to the running origin, which is right on the deployed
  /// host — but an admin printing from a dev server would otherwise bake
  /// `localhost` into physical stickers, so the print dialog lets it be
  /// overridden and warns about that case.
  static String qrPayloadFor(
    String tableId, {
    String? chairId,
    String? origin,
  }) {
    final base = (origin == null || origin.trim().isEmpty)
        ? currentOrigin()
        : origin.trim();
    final query = {
      't': tableId,
      if (chairId != null && chairId.isNotEmpty) 'c': chairId,
    };
    return Uri.parse('${_stripTrailingSlash(base)}/scan')
        .replace(queryParameters: query)
        .toString();
  }

  /// `Uri.base` throws for non-http schemes (e.g. a `file://` load), so this
  /// never lets a bad origin take down the admin page.
  static String currentOrigin() {
    try {
      return Uri.base.origin;
    } catch (_) {
      return '';
    }
  }

  /// True when the origin would produce QR codes that only work on the machine
  /// that printed them.
  static bool isLocalOrigin(String origin) {
    final lower = origin.toLowerCase();
    return lower.contains('localhost') ||
        lower.contains('127.0.0.1') ||
        lower.contains('0.0.0.0');
  }

  static String _stripTrailingSlash(String value) =>
      value.endsWith('/') ? value.substring(0, value.length - 1) : value;

  /// Interprets whatever a scanner read.
  ///
  /// Accepts either QR this app generates — `?t=…&c=…` (the seat's ids) and
  /// `?n=…` (the number printed on the chair) — from any origin, since only
  /// the query matters, so codes printed against an old domain keep working.
  /// Anything else falls back to being treated as a table name, which is how
  /// every QR code printed before this feature existed behaves.
  static ScanPayload parseScanPayload(String raw) {
    final text = raw.trim();
    if (text.isEmpty) return const ScanPayload();

    final uri = Uri.tryParse(text);
    if (uri != null && uri.queryParameters.isNotEmpty) {
      final tableId = uri.queryParameters['t'];
      if (tableId != null && tableId.isNotEmpty) {
        final chairId = uri.queryParameters['c'];
        return ScanPayload(tableId: tableId, chairId: chairId);
      }
      // A sticker printed with the chair's number on it.
      final chairNo = int.tryParse(uri.queryParameters['n'] ?? '');
      if (chairNo != null) return ScanPayload(chairNo: chairNo);
    }

    return ScanPayload(plainText: text);
  }

  // -------------------------------------------------------------- numbering

  /// The next free chair number restaurant-wide. Auto-generation continues
  /// from here so numbers never repeat across tables.
  static Future<int> nextChairNumber() async {
    final tables = await loadTables();
    return nextChairNumberIn(tables);
  }

  static int nextChairNumberIn(List<TableDoc> tables) {
    var highest = 0;
    for (final table in tables) {
      for (final chair in table.chairs) {
        if (chair.no > highest) highest = chair.no;
      }
    }
    return highest + 1;
  }

  /// The table already using [chairNo], ignoring [exceptTableId] (the table
  /// being edited). Used to block duplicates with a message that names the
  /// clashing table.
  static TableDoc? tableUsingChairNumber(
    List<TableDoc> tables,
    int chairNo, {
    String? exceptTableId,
  }) {
    for (final table in tables) {
      if (table.id == exceptTableId) continue;
      for (final chair in table.chairs) {
        if (chair.no == chairNo) return table;
      }
    }
    return null;
  }

  // --------------------------------------------------------------- writing

  static Future<String> createTable({
    required String name,
    required int sortOrder,
    required List<ChairEntry> chairs,
  }) async {
    final doc = await _collection.add({
      'name': name,
      'sortOrder': sortOrder,
      'chairs': chairs.map((c) => c.toMap()).toList(),
      'createdAt': FieldValue.serverTimestamp(),
    });
    return doc.id;
  }

  static Future<void> updateTable({
    required String tableId,
    required String name,
    required int sortOrder,
    required List<ChairEntry> chairs,
  }) {
    return _collection.doc(tableId).set({
      'name': name,
      'sortOrder': sortOrder,
      'chairs': chairs.map((c) => c.toMap()).toList(),
    }, SetOptions(merge: true));
  }

  static Future<void> deleteTable(String tableId) =>
      _collection.doc(tableId).delete();

  /// Builds [count] chairs numbered consecutively from [startNo].
  static List<ChairEntry> generateChairs({
    required int count,
    required int startNo,
  }) {
    return List.generate(
      count,
      (i) => ChairEntry(id: '${ChairEntry.newId()}_$i', no: startNo + i),
    );
  }
}
