// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEqWRtEph-6QYr8JLNZfv2LFZ5cYevbFE',
    appId: '1:382479866723:web:90e95d1ef4a417a0a65156',
    messagingSenderId: '382479866723',
    projectId: 'agan-ee7ee',
    authDomain: 'agan-ee7ee.firebaseapp.com',
    storageBucket: 'agan-ee7ee.firebasestorage.app',
    measurementId: 'G-SKT6V90WC3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA20KbaJiIdbeciPSgXhEyD1x9EZ24Kz18',
    appId: '1:382479866723:android:2cc0773a7657b594a65156',
    messagingSenderId: '382479866723',
    projectId: 'agan-ee7ee',
    storageBucket: 'agan-ee7ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCFDx1LytYswBi4GzQaLH0E67SY2xa8yE',
    appId: '1:382479866723:ios:2b37824b2ef11a5ca65156',
    messagingSenderId: '382479866723',
    projectId: 'agan-ee7ee',
    storageBucket: 'agan-ee7ee.firebasestorage.app',
    iosBundleId: 'com.example.restorant',
  );
}
